FROM node:12.18.1-alpine AS builder
WORKDIR /app
COPY . .
RUN npm rebuild node-sass
RUN npm install
RUN npm rebuild node-sass
RUN npm run build

FROM nginx:1.17.1-alpine AS prod-stage
COPY --from=builder /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
